import {
  type EmitContext,
  emitFile,
  getNamespaceFullName,
  type Program,
} from "@typespec/compiler";
import {
  collectServices,
  type RpcInfo,
  type ServiceInfo,
  toSnakeCase,
  toScreamingSnakeCase,
} from "@speconn/typespec-emitter-core";

export type EmitterOptions = {
  "emitter-output-dir": string;
  "target"?: "both" | "client" | "server";
};

async function emitRust(program: Program, services: ServiceInfo[], outputDir: string, target: "both" | "client" | "server"): Promise<void> {
  const promises: Promise<void>[] = [];

  for (const svc of services) {
    if (svc.rpcs.length === 0) continue;
    const snake = toSnakeCase(svc.serviceName);
    const nsPath = getNamespaceFullName(svc.namespace);
    const typesSnake = nsPath.split('.').map(toSnakeCase).join('_');
    const typesModPath = `crate::${typesSnake}_types`;
    const reqName = (rpc: RpcInfo) => rpc.inputType?.name ?? "()";
    const resName = (rpc: RpcInfo) => rpc.outputType?.name ?? "()";
    const reqCodec = (rpc: RpcInfo) => rpc.inputType ? `&${rpc.inputType.name}Codec` : "specodec::EMPTY_CODEC";
    const resCodec = (rpc: RpcInfo) => rpc.outputType ? `&${rpc.outputType.name}Codec` : "specodec::EMPTY_CODEC";
    const constPfx = toScreamingSnakeCase(svc.serviceName);

    // ---- server ----
    const server: string[] = [];
    server.push("// Generated by @speconn/typespec-emitter-rust. DO NOT EDIT.\n");
    const serverTypeImports = svc.rpcs.flatMap(rpc => [rpc.inputType?.name, rpc.outputType?.name]).filter(Boolean) as string[];
    const _procConsts = svc.rpcs.map(rpc => `${constPfx}_${toScreamingSnakeCase(rpc.originalName)}_PROCEDURE`);
    const codecImports = svc.rpcs.flatMap(rpc => [
      rpc.inputType ? `${rpc.inputType.name}Codec` : null,
      rpc.outputType ? `${rpc.outputType.name}Codec` : null,
    ]).filter(Boolean) as string[];
    const allImports = [...new Set([...serverTypeImports, ...codecImports])];
    server.push(`use ${typesModPath}::{${allImports.join(", ")}};`);
    server.push(`use speconn_runtime_rust::{SpeconnRouter, SpeconnContext, SpeconnError};\n`);
    for (const rpc of svc.rpcs) {
      server.push(`pub const ${constPfx}_${toScreamingSnakeCase(rpc.originalName)}_PROCEDURE: &str = "${rpc.path}";`);
    }
    server.push('');
    server.push(`pub fn ${snake}_router(`);
    for (const rpc of svc.rpcs) {
      if (rpc.isStream) {
        server.push(`    ${rpc.name}_fn: impl Fn(&SpeconnContext, ${reqName(rpc)}, Box<dyn Fn(${resName(rpc)}) + Send + Sync>) -> Result<(), SpeconnError> + Send + Sync + 'static,`);
      } else {
        server.push(`    ${rpc.name}_fn: impl Fn(&SpeconnContext, ${reqName(rpc)}) -> Result<${resName(rpc)}, SpeconnError> + Send + Sync + 'static,`);
      }
    }
    server.push(`) -> SpeconnRouter {`);
    server.push(`    SpeconnRouter::new()`);
    for (const rpc of svc.rpcs) {
      const proc = `${constPfx}_${toScreamingSnakeCase(rpc.originalName)}_PROCEDURE`;
      const method = rpc.isStream ? "server_stream" : "unary";
      server.push(`        .${method}(${proc}, ${reqCodec(rpc)}, ${resCodec(rpc)}, ${rpc.name}_fn)`);
    }
    server.push(`}\n`);

    // ---- client ----
    const client: string[] = [];
    client.push("// Generated by @speconn/typespec-emitter-rust. DO NOT EDIT.\n");
    const clientTypeImports = svc.rpcs.flatMap(rpc => [rpc.inputType?.name, rpc.outputType?.name]).filter(Boolean) as string[];
    const clientCodecImports = svc.rpcs.flatMap(rpc => [
      rpc.inputType ? `${rpc.inputType.name}Codec` : null,
      rpc.outputType ? `${rpc.outputType.name}Codec` : null,
    ]).filter(Boolean) as string[];
    const _clientProcConsts = svc.rpcs.map(rpc => `${constPfx}_${toScreamingSnakeCase(rpc.originalName)}_PROCEDURE`);
    const allClientImports = [...new Set([...clientTypeImports, ...clientCodecImports])];
    client.push(`use ${typesModPath}::{${allClientImports.join(", ")}};`);
    client.push(`use speconn_runtime_rust::{SpeconnError, CallOptions, Response, StreamResponse};\n`);
    for (const rpc of svc.rpcs) {
      client.push(`const ${constPfx}_${toScreamingSnakeCase(rpc.originalName)}_PROCEDURE: &str = "${rpc.path}";`);
    }
    client.push('');
    client.push(`pub struct ${svc.serviceName}Client<T: speconn_runtime_rust::SpeconnChannel + Clone> {`);
    for (const rpc of svc.rpcs) {
      client.push(`    ${rpc.name}: speconn_runtime_rust::SpeconnClient<T>,`);
    }
    client.push('}\n');
    client.push(`impl<T: speconn_runtime_rust::SpeconnChannel + Clone> ${svc.serviceName}Client<T> {`);
    client.push(`    pub fn new(base_url: &str, transport: T) -> Self {`);
    client.push(`        Self {`);
    for (const rpc of svc.rpcs) {
      const proc = `${constPfx}_${toScreamingSnakeCase(rpc.originalName)}_PROCEDURE`;
      client.push(`            ${rpc.name}: speconn_runtime_rust::SpeconnClient::new(base_url, ${proc}, transport.clone()),`);
    }
    client.push(`        }`);
    client.push(`    }`);
    for (const rpc of svc.rpcs) {
      if (rpc.isStream) {
        client.push(`    pub async fn ${rpc.name}(&self, req: ${reqName(rpc)}, options: CallOptions) -> Result<StreamResponse<${resName(rpc)}>, SpeconnError> {`);
        client.push(`        self.${rpc.name}.stream(${reqCodec(rpc)}, &req, ${resCodec(rpc)}, options).await`);
      } else {
        client.push(`    pub async fn ${rpc.name}(&self, req: ${reqName(rpc)}, options: CallOptions) -> Result<Response<${resName(rpc)}>, SpeconnError> {`);
        client.push(`        self.${rpc.name}.call(${reqCodec(rpc)}, &req, ${resCodec(rpc)}, options).await`);
      }
      client.push(`    }`);
    }
    client.push('}\n');
    client.push(`impl ${svc.serviceName}Client<speconn_runtime_rust::ReqwestChannel> {`);
    client.push(`    pub fn new_default(base_url: &str) -> Self { Self::new(base_url, speconn_runtime_rust::ReqwestChannel::new(base_url)) }`);
    client.push('}\n');

    if (target !== "client") promises.push(emitFile(program, { path: `${outputDir}/${snake}_server.rs`, content: server.join("\n") }));
    if (target !== "server") promises.push(emitFile(program, { path: `${outputDir}/${snake}_client.rs`, content: client.join("\n") }));
  }

  // Generate mod.rs to declare all generated modules
  if (services.length > 0) {
    const modLines: string[] = [];
    modLines.push("// Generated by @speconn/typespec-emitter-rust. DO NOT EDIT.");
    const declared = new Set<string>();
    for (const svc of services) {
      const snake = toSnakeCase(svc.serviceName);
      const nsPath = getNamespaceFullName(svc.namespace);
      const typesSnake = nsPath.split('.').map(toSnakeCase).join('_');
      if (!declared.has(`${typesSnake}_types`)) {
        modLines.push(`pub mod ${typesSnake}_types;`);
        declared.add(`${typesSnake}_types`);
      }
      if (target !== "client") modLines.push(`pub mod ${snake}_server;`);
      if (target !== "server") modLines.push(`pub mod ${snake}_client;`);
    }
    modLines.push("");
    promises.push(emitFile(program, { path: `${outputDir}/mod.rs`, content: modLines.join("\n") }));
  }

  await Promise.all(promises);
}

export async function $onEmit(context: EmitContext<EmitterOptions>) {
  const services = collectServices(context.program);
  const target = (context.options["target"] ?? "both") as "both" | "client" | "server";
  await emitRust(context.program, services, context.emitterOutputDir, target);
}
